//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdDotbaoduong
    {
        public int IdDotBaoDuong { get; set; }
        public Nullable<int> IDCar { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public Nullable<int> SokmDau { get; set; }
        public Nullable<int> SoKmCuoi { get; set; }
        public Nullable<int> SoKmHientai { get; set; }
    }
}
