//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdHanhtrinhbaotri
    {
        public int IDHanhTrinhBaoTri { get; set; }
        public Nullable<int> Sokm { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> IDDotbaoduong { get; set; }
    }
}
