//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdSendMail
    {
        public int SendmailId { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public Nullable<int> IdCar { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
