//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdService
    {
        public int IdService { get; set; }
        public string NameService { get; set; }
        public Nullable<int> IdCar { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> Type { get; set; }
        public string Ghichu { get; set; }
    }
}
