//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbConfig
    {
        public int ConfigID { get; set; }
        public Nullable<int> TG40 { get; set; }
        public Nullable<int> TG80 { get; set; }
        public Nullable<double> TimeTracking { get; set; }
        public Nullable<int> TimeDelivery { get; set; }
        public Nullable<int> TimeAccountant { get; set; }
        public string ApiUrl { get; set; }
    }
}
