//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPermission_Menu
    {
        public int ID { get; set; }
        public int PermissionID { get; set; }
        public int MenuID { get; set; }
        public int STT { get; set; }
    }
}
