//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTheTai
    {
        public int ThetaiID { get; set; }
        public string MaThe { get; set; }
        public string MaPhieu { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> KPI { get; set; }
        public Nullable<System.DateTime> Luotdi { get; set; }
        public Nullable<System.DateTime> Luotve { get; set; }
    }
}
