//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUSer
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string Description { get; set; }
        public int PermissionID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> Status { get; set; }
        public string Code { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    }
}
